name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # to create release

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack NuGet packages
      run: |
        dotnet pack DbfSharp.ConsoleAot/DbfSharp.ConsoleAot.csproj --configuration Release --no-build --output ./artifacts
        dotnet pack DbfSharp.Core/DbfSharp.Core.csproj --configuration Release --no-build --output ./artifacts

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  build-executables:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            artifact-name: dbfsharp-linux-x64
          - os: windows-latest
            rid: win-x64
            artifact-name: dbfsharp-win-x64
          - os: windows-latest
            rid: win-arm64
            artifact-name: dbfsharp-win-arm64
          - os: macos-13
            rid: osx-x64
            artifact-name: dbfsharp-osx-x64
          - os: macos-latest
            rid: osx-arm64
            artifact-name: dbfsharp-osx-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish self-contained executable
      run: dotnet publish DbfSharp.ConsoleAot/DbfSharp.ConsoleAot.csproj --configuration Release --runtime ${{ matrix.rid }} --self-contained true --output ./publish/${{ matrix.artifact-name }}

    - name: Create archive (Windows)
      if: startsWith(matrix.rid, 'win-')
      shell: pwsh
      run: Compress-Archive -Path ./publish/${{ matrix.artifact-name }} -DestinationPath ./publish/${{ matrix.artifact-name }}.zip

    - name: Create archive (Unix)
      if: "!startsWith(matrix.rid, 'win-')"
      shell: bash
      run: |
        cd ./publish
        tar -czf ${{ matrix.artifact-name }}.tar.gz ${{ matrix.artifact-name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: ./publish/${{ matrix.artifact-name }}.*

  create-release:
    needs: [publish-nuget, build-executables]
    runs-on: ubuntu-latest

    steps:
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./release-artifacts

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        generateReleaseNotes: true
        draft: false
        prerelease: false
        artifacts: ./release-artifacts/*/*
